package com.precious.syncres.shared.exception;

import lombok.Getter;

@Getter
public enum ErrorCode {
    JD_INPUT_REQUIRED,
    JD_SCRAPE_FAILED,
    CV_NOT_FOUND,
    APPLICATION_NOT_FOUND,
    CV_IN_USE,
    INVALID_STATUS_TRANSITION,
    STATUS_IS_TERMINAL,
    AI_SCORER_ERROR,
    AI_REWRITER_ERROR,
    PDF_GENERATION_ERROR,
    FILE_TOO_LARGE,
    UNSUPPORTED_FILE_TYPE,
    DOWNLOAD_EXPIRED,
    DOWNLOAD_INVALID_SIGNATURE,
    EMAIL_ALREADY_REGISTERED,
    EMAIL_NOT_VERIFIED,
    OTP_INVALID,
    OTP_EXPIRED,
    CV_INPUT_REQUIRED,
    JOB_NOT_FOUND,
    ACCESS_DENIED,
    JOB_ACCESS_DENIED,
    INTERNAL_SERVER_ERROR
}
