# Production Overrides
spring.datasource.url=jdbc:postgresql://postgres:5432/syncres

# Logging
logging.level.root=WARN
logging.level.com.precious.syncres=INFO

# JobRunr
org.jobrunr.dashboard.enabled=false
